Test clippy again

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -27,12 +27,10 @@ jobs:
         uses: mozilla-actions/sccache-action@v0.0.3
         with:
           version: "v0.4.0"
-      - name: Run cargo check
-        run: cargo check
-      - name: Run cargo fmt check
+      - name: Run lint
         run: |
-          if ! cargo fmt --all --check ; then
-            echo "Formatting errors detected, please run 'cargo fmt --all' to fix it";
+          if ! make lint ; then
+            echo "Linting or formatting errors detected, please run 'make lint-fix' to fix it";
             exit 1
           fi
 
@@ -56,8 +54,8 @@ jobs:
       - name: Run cargo fmt check
         run: |
           cd examples/demo-prover;
-          if ! make lint ; then
-            echo "Formatting errors detected, please run 'make lint-fix' to fix it";
+          if ! cargo fmt --check ; then
+            echo "Formatting errors detected, please run 'cargo fmt' to fix it";
             exit 1
           fi
 
