trying until instead of while

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -127,24 +127,16 @@ jobs:
       - name: start sovereign demo-rollup
         working-directory: ./examples/demo-rollup
         run: cargo run &
+
       - name: wait for service to be up
         run: |
           SECONDS=0
-          while [ $SECONDS -lt 600 ]
+          until curl -s -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"bank_balanceOf","params":["sov15vspj48hpttzyvxu8kzq5klhvaczcpyxn6z6k0hwpwtzs4a6wkvqmlyjd6","sov16m8fxq0x5wc5aw75fx9rus2p7g2l22zf4re72c3m058g77cdjemsgscxvf"],"id":1}' http://127.0.0.1:12345; [ $? -eq 0 ] || [ $SECONDS -ge 600 ]
           do
-            RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"bank_balanceOf","params":["sov15vspj48hpttzyvxu8kzq5klhvaczcpyxn6z6k0hwpwtzs4a6wkvqmlyjd6","sov16m8fxq0x5wc5aw75fx9rus2p7g2l22zf4re72c3m058g77cdjemsgscxvf"],"id":1}' http://127.0.0.1:12345)
-            STATUS=$?
-            echo "Curl response: $RESPONSE"
-            echo "Curl exit status: $STATUS"
-            if [ $STATUS -ne 0 ]
-            then
-              echo "Curl failed, sleeping for 5 seconds..."
-              sleep 5
-            else
-              echo "Curl succeeded, breaking loop..."
-              break
-            fi
+            echo "Curl failed or server not ready yet, sleeping for 5 seconds..."
+            sleep 5
           done
+
       - name: submit rollup transaction
         run: make test-create-token
       - name: evaluate result
