Add cargo fmt check (#184)
* Add fmt check

* Fix formatting

* Add helper message to failed CI formatting job

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -19,6 +19,12 @@ jobs:
       - uses: Swatinem/rust-cache@v2.2.0
       - name: Run cargo check
         run: cargo check
+      - name: Run cargo fmt check
+        run: |
+          if ! cargo fmt --check ; then
+            echo "Formatting errors detected, please rune `cargo fmt` to fix it";
+            exit 1
+          fi
 
   test:
     runs-on: ubuntu-latest
